{
 "title": "3MTZ - Visao Geral Aplicacoes",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "grupo",
    "query": {}
   },
   {
    "name": "host_url",
    "query": {}
   },
   {
    "name": "host_aeroports",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Informacoes gerais do sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 1 },
   "repeat": "host_url",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Webcheck" },
     "group": { "filter": "$grupo" },
     "host": {
      "filter": "/http://desafiozabbix.com.br/api/$host_url/"
     },
     "item": {
      "filter": "Response code for step \"Tempo de resposta\" of scenario \"Verifica disponibilidade\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Webcheck" },
     "group": { "filter": "$grupo" },
     "host": {
      "filter": "/http://desafiozabbix.com.br/api/$host_url/"
     },
     "item": {
      "filter": "Response code for step \"Tempo de resposta\" of scenario \"Verifica disponibilidade\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Webcheck" },
     "group": { "filter": "$grupo" },
     "host": {
      "filter": "/http://desafiozabbix.com.br/api/$host_url/"
     },
     "item": {
      "filter": "Response code for step \"Tempo de resposta\" of scenario \"Verifica disponibilidade\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo de resposta das aplicacoes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "Webcheck" },
     "functions": [
      {
       "$$hashKey": "object:631",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)/",
        "$__zbx_host_name - Checkin"
       ],
       "text": "replaceAlias(/(.*)/, $__zbx_host_name - Checkin)"
      }
     ],
     "group": { "filter": "3MTZ/API" },
     "host": {
      "filter": "http://desafiozabbix.com.br/api/checkins"
     },
     "item": {
      "filter": "Response time for step \"Tempo de resposta\" of scenario \"Verifica disponibilidade\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Webcheck" },
     "functions": [
      {
       "$$hashKey": "object:715",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)/",
        "$__zbx_host_name - Boardings"
       ],
       "text": "replaceAlias(/(.*)/, $__zbx_host_name - Boardings)"
      }
     ],
     "group": { "filter": "3MTZ/API" },
     "host": {
      "filter": "http://desafiozabbix.com.br/api/boardings"
     },
     "item": {
      "filter": "Response time for step \"Tempo de resposta\" of scenario \"Verifica disponibilidade\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Webcheck" },
     "functions": [
      {
       "$$hashKey": "object:719",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)/",
        "$__zbx_host_name - Checkin"
       ],
       "text": "replaceAlias(/(.*)/, $__zbx_host_name - Checkin)"
      }
     ],
     "group": { "filter": "3MTZ/API" },
     "host": {
      "filter": "http://desafiozabbix.com.br/api/baggagechecks"
     },
     "item": {
      "filter": "Response time for step \"Tempo de resposta\" of scenario \"Verifica disponibilidade\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$host_aeroports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "host_aeroports",
   "collapsed": true,
   "panels": [
    {
     "title": "$host_aeroports - Checkins",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2237",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - Now"
         ],
         "text": "replaceAlias(/(.*)/, $1 - Now)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Checkins" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2258",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Checkins" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2309",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        },
        {
         "$$hashKey": "object:2312",
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - D-1"
         ],
         "text": "replaceAlias(/(.*)/, $1 - D-1)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Checkins" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "$host_aeroports - Embarques",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2463",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - Now"
         ],
         "text": "replaceAlias(/(.*)/, $1 - Now)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Embarques" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2484",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        },
        {
         "$$hashKey": "object:2485",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - D-1"
         ],
         "text": "replaceAlias(/(.*)/, $1 - D-1)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Embarques" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "$host_aeroports - Despacho de Bagagens",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2635",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - Now"
         ],
         "text": "replaceAlias(/(.*)/, $1 - Now)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": {
        "filter": "Quantidade Despacho de bagagens"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2656",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        },
        {
         "$$hashKey": "object:2657",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - D-1"
         ],
         "text": "replaceAlias(/(.*)/, $1 - D-1)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": {
        "filter": "Quantidade Despacho de bagagens"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "$host_aeroports - Problems Kiosk",
     "type": "stat",
     "gridPos": { "h": 3, "w": 18, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 4
       }
      }
     ]
    }
   ]
  },
  {
   "title": "$host_aeroports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host_aeroports - Checkins",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2237",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - Now"
         ],
         "text": "replaceAlias(/(.*)/, $1 - Now)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Checkins" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2258",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Checkins" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2309",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        },
        {
         "$$hashKey": "object:2312",
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - D-1"
         ],
         "text": "replaceAlias(/(.*)/, $1 - D-1)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Checkins" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "$host_aeroports - Embarques",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2463",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - Now"
         ],
         "text": "replaceAlias(/(.*)/, $1 - Now)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Embarques" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2484",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        },
        {
         "$$hashKey": "object:2485",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - D-1"
         ],
         "text": "replaceAlias(/(.*)/, $1 - D-1)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Embarques" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "$host_aeroports - Despacho de Bagagens",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2635",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - Now"
         ],
         "text": "replaceAlias(/(.*)/, $1 - Now)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": {
        "filter": "Quantidade Despacho de bagagens"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2656",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        },
        {
         "$$hashKey": "object:2657",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - D-1"
         ],
         "text": "replaceAlias(/(.*)/, $1 - D-1)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": {
        "filter": "Quantidade Despacho de bagagens"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "$host_aeroports - Problems Kiosk",
     "type": "stat",
     "gridPos": { "h": 3, "w": 18, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 4
       }
      }
     ]
    }
   ]
  },
  {
   "title": "$host_aeroports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host_aeroports - Checkins",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2237",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - Now"
         ],
         "text": "replaceAlias(/(.*)/, $1 - Now)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Checkins" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2258",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Checkins" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2309",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        },
        {
         "$$hashKey": "object:2312",
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - D-1"
         ],
         "text": "replaceAlias(/(.*)/, $1 - D-1)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Checkins" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "$host_aeroports - Embarques",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2463",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - Now"
         ],
         "text": "replaceAlias(/(.*)/, $1 - Now)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Embarques" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2484",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        },
        {
         "$$hashKey": "object:2485",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - D-1"
         ],
         "text": "replaceAlias(/(.*)/, $1 - D-1)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "Quantidade de Embarques" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "$host_aeroports - Despacho de Bagagens",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2635",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - Now"
         ],
         "text": "replaceAlias(/(.*)/, $1 - Now)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": {
        "filter": "Quantidade Despacho de bagagens"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Aeroporto" },
       "functions": [
        {
         "$$hashKey": "object:2656",
         "def": {
          "category": "Time",
          "defaultParams": [ "24h" ],
          "name": "timeShift",
          "params": [
           {
            "name": "interval",
            "options": [
             "24h",
             "7d",
             "1M",
             "+24h",
             "-24h"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "24h" ],
         "text": "timeShift(24h)"
        },
        {
         "$$hashKey": "object:2657",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 - D-1"
         ],
         "text": "replaceAlias(/(.*)/, $1 - D-1)"
        }
       ],
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": {
        "filter": "Quantidade Despacho de bagagens"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "$host_aeroports - Problems Kiosk",
     "type": "stat",
     "gridPos": { "h": 3, "w": 18, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$grupo" },
       "host": { "filter": "$host_aeroports" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 4
       }
      }
     ]
    }
   ]
  }
 ]
}